<template>


  <div>


    <el-row>
      <el-col :span="16" :offset="4">




    <h1><span style="color: rgb(0, 0, 0);">1. </span><a href="https://www.cnblogs.com/anxminise/p/9808279.html" target="_blank"><span style="color: rgb(0, 0, 0);">CORS跨域</span></a></h1><h2>1.1 什么是跨域</h2><p><span style="color: rgb(245, 34, 45);">跨域是指：</span><strong>浏览器A</strong>从<strong>服务器B</strong>获取的静态资源，包括Html、Css、Js，然后在<strong>Js</strong>中通过<strong>Ajax</strong>访问<strong>C服务器</strong>的静态资源或请求。即：浏览器A从B服务器拿的资源，资源中想访问服务器C的资源。</p><p><span style="color: rgb(245, 34, 45);">同源策略是指：</span><strong>浏览器A</strong>从<strong>服务器B</strong>获取的静态资源，包括Html、Css、Js，为了用户安全，浏览器加了限制，其中的<strong>Js</strong>通过<strong>Ajax</strong>只能访问<strong>B服务器</strong>的静态资源或请求。即：浏览器A从哪拿的资源，那资源中就只能访问哪。</p><p>同源是指：同一个请求协议(如：Http或Https)、同一个Ip、同一个端口，3个全部相同，即为同源</p><h2>1.2 跨域的处理</h2><p>跨域的这种需求还是有的，因此，<a href="https://www.w3.org/" target="_blank">W3C</a>组织制定了一个<a href="https://www.w3.org/TR/cors/" target="_blank">Cross-Origin Resource Sharing</a>规范，简写为<code>Cors</code>，现在这个规范已经被大多数浏览器支持，从而，处理跨域的需求。</p><p>Cors需要在后端应用进行配置，因此，是一种跨域的后端处理方式，这么做也容易理解，一个你不认识的源来访问你的应用，自然需要应用进行授权。除了后端处理方式，也有前端的解决方案，如：JSONP，因这里我们主要讲解SpringBoot2.x对Cors的配置，暂不对前端解决方案进行详细说明。</p><h2>1.3 跨域的分类</h2><p>域分为以下3种：</p><div class="simditor-table"><table><thead><tr><td>名称</td><td>英文名</td><td>说明</td></tr></thead><tbody><tr><td>简单请求</td><td>Simple Request</td><td>发起的Http请求符合：<br>1.无自定义请求头，<br>2.请求动词为GET、HEAD或POST之一，<br>3.动词为POST时，Content-Type是application/x-www-form-urlencoded，<br>multipart/form-data或text/plain之一</td></tr><tr><td>预检请求</td><td>Preflighted Request</td><td>发起的Http请求符合其中之一：<br>1.包含了自定义请求头，<br>2.请求动词不是GET、HEAD或POST，<br>3.动词是POST时， Content-Type不是application/x-www-form-urlencoded，<br>multipart/form-data或text/plain。 即：简单请求的相反</td></tr><tr><td>凭证请求</td><td>Requests with Credential</td><td>发起的Http请求中带有凭证</td></tr></tbody></table><div class="simditor-resize-handle" contenteditable="false" style="display: none;"></div></div><h2>1.4 SpringBoot2.x配置CORS</h2><h3>1.4.1 使用@CrossOrigin注解</h3><p>代码实例</p><pre><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="cm-meta" style="color: rgb(31, 127, 154); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">@RestController</span>
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="cm-meta" style="color: rgb(31, 127, 154); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">@RequestMapping</span>(<span class="cm-variable" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">value</span> <span class="cm-operator" style="color: rgb(215, 58, 73); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">=</span> <span class="cm-string" style="color: rgb(102, 153, 0); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">"/api/users"</span>)
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="cm-meta" style="color: rgb(31, 127, 154); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">@CrossOrigin</span>
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="cm-keyword" style="color: rgb(215, 58, 73); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">public</span> <span class="cm-keyword" style="color: rgb(215, 58, 73); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">class</span> <span class="cm-def" style="color: rgb(0, 92, 197); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">UsersController</span>{
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">    <span class="cm-meta" style="color: rgb(31, 127, 154); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">@Autowired</span>
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">    <span class="cm-keyword" style="color: rgb(215, 58, 73); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">private</span> <span class="cm-variable" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">UsersService</span> <span class="cm-variable" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">usersService</span>;
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">    <span class="cm-meta" style="color: rgb(31, 127, 154); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">@PostMapping</span>
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">    <span class="cm-meta" style="color: rgb(31, 127, 154); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">@CrossOrigin</span>
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">    <span class="cm-keyword" style="color: rgb(215, 58, 73); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">public</span> <span class="cm-variable" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">User</span> <span class="cm-variable" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">create</span>(<span class="cm-meta" style="color: rgb(31, 127, 154); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">@RequestBody</span> <span class="cm-variable" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">User</span> <span class="cm-variable" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">user</span>) {
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">        <span class="cm-keyword" style="color: rgb(215, 58, 73); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">return</span> <span class="cm-variable" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">userService</span>.<span class="cm-variable" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">save</span>(<span class="cm-variable" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">user</span>);
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">    }
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">}</span></span></pre><p>其中，@CrossOrigin注解可以使用以下参数</p><div class="simditor-table"><table><thead><tr><td>名称</td><td>类型</td><td>范围</td><td>必填</td><td>请求头字段</td></tr></thead><tbody><tr><td>value</td><td>String数组</td><td>类或方法</td><td>是</td><td>Access-Control-Allow-Origin</td></tr><tr><td>origins</td><td>String数组</td><td>类或方法</td><td>是，同value，可以二选一</td><td>Access-Control-Allow-Origin</td></tr><tr><td>methods</td><td>String数组</td><td>类或接口</td><td>是</td><td>Access-Control-Allow-Methods</td></tr><tr><td>maxAge</td><td>long</td><td>类或接口</td><td>否</td><td>Access-Control-Max-Age</td></tr><tr><td>allowCredentials</td><td>String</td><td>类或接口</td><td>否</td><td>Access-Control-Allow-Credentials</td></tr><tr><td>allowedHeaders</td><td>String数组</td><td>类或接口</td><td>否</td><td>Access-Control-Request-Headers</td></tr><tr><td>exposedHeaders</td><td>String数组</td><td>类或接口</td><td>否</td><td>Access-Control-Expose-Headers</td></tr></tbody></table><div class="simditor-resize-handle" contenteditable="false"></div></div><ul><li>备注说明</li></ul><ol><li>value、origins属性：配置允许访问的源，如: <a href="http://anxminise.cc/" target="_blank">http://anxminise.cc</a>，<code>*</code>表示允许全部的域名</li><li>methods属性：配置跨域请求支持的方式，如：GET、POST，且一次性返回全部支持的方式</li><li>maxAge属性：配置预检请求的有效时间， 单位是秒，表示：在多长时间内，不需要发出第二次预检请求</li><li>allowCredentials属性：配置是否允许发送Cookie，用于 凭证请求， 默认不发送cookie</li><li>allowedHeaders属性：配置允许的自定义请求头，用于 预检请求</li><li>exposedHeaders属性：配置响应的头信息， 在其中可以设置其他的头信息，不进行配置时， 默认可以获取到Cache-Control、Content-Language、Content-Type、Expires、Last-Modified、Pragma字段</li></ol><h3>1.4.2 使用WebMvcConfigurer对象</h3><p>代码实例</p><pre><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="cm-meta" style="color: rgb(31, 127, 154); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">@Configuration</span>
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="cm-keyword" style="color: rgb(215, 58, 73); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">public</span> <span class="cm-keyword" style="color: rgb(215, 58, 73); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">class</span> <span class="cm-def" style="color: rgb(0, 92, 197); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">WebMvcConfig</span> <span class="cm-keyword" style="color: rgb(215, 58, 73); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">extends</span> <span class="cm-variable" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">WebMvcConfigurationSupport</span> {
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">    <span class="cm-comment" style="color: rgb(106, 115, 125); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">/**</span>
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">     <span class="cm-comment" style="color: rgb(106, 115, 125); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">* 允许跨域</span>
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">     <span class="cm-comment" style="color: rgb(106, 115, 125); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">* @param registry</span>
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">     <span class="cm-comment" style="color: rgb(106, 115, 125); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">*/</span>
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">    <span class="cm-meta" style="color: rgb(31, 127, 154); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">@Override</span>
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">    <span class="cm-keyword" style="color: rgb(215, 58, 73); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">protected</span> <span class="cm-type" style="color: rgb(34, 134, 58); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">void</span> <span class="cm-variable" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">addCorsMappings</span>(<span class="cm-variable" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">CorsRegistry</span> <span class="cm-variable" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">registry</span>) {
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">        <span class="cm-variable" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">registry</span>.<span class="cm-variable" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">addMapping</span>(<span class="cm-string" style="color: rgb(102, 153, 0); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">"/**"</span>)
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">                .<span class="cm-variable" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">allowedHeaders</span>(<span class="cm-string" style="color: rgb(102, 153, 0); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">"*"</span>)
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">                .<span class="cm-variable" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">allowedOrigins</span>(<span class="cm-string" style="color: rgb(102, 153, 0); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">"*"</span>)
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">                .<span class="cm-variable" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">allowCredentials</span>(<span class="cm-atom" style="color: rgb(153, 0, 85); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">true</span>)
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">                .<span class="cm-variable" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">allowedMethods</span>(<span class="cm-string" style="color: rgb(102, 153, 0); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">"GET"</span>, <span class="cm-string" style="color: rgb(102, 153, 0); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">"POST"</span>, <span class="cm-string" style="color: rgb(102, 153, 0); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">"DELETE"</span>, <span class="cm-string" style="color: rgb(102, 153, 0); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">"PUT"</span>, <span class="cm-string" style="color: rgb(102, 153, 0); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">"PATCH"</span>)
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">                .<span class="cm-variable" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">maxAge</span>(<span class="cm-number" style="color: rgb(0, 92, 197); background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">3600</span>);
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">    }
</span></span><span class="lake-preview-line" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);"><span class="lake-preview-codeblock-content" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0);">}</span></span></pre><p>其中，通过相应的方法实现跨域请求的配置</p><div class="simditor-table"><table><thead><tr><td>方法类</td><td>方法名称</td><td>必填</td><td>请求头字段</td><td>说明</td></tr></thead><tbody><tr><td>CorsRegistry</td><td>addMapping</td><td>是</td><td>无, 非Cors属性,<br>属于SpringBoot配置</td><td>配置支持跨域的路径</td></tr><tr><td>CorsRegistration</td><td>allowedOrigins</td><td>是</td><td>Access-Control-Allow-Origin</td><td>配置允许的源</td></tr><tr><td>CorsRegistration</td><td>allowedMethods</td><td>是</td><td>Access-Control-Allow-Methods</td><td>配置支持跨域请求的方法,<br>如：GET、POST，一次性返回</td></tr><tr><td>CorsRegistration</td><td>maxAge</td><td>否</td><td>Access-Control-Max-Age</td><td>配置预检请求的有效时间</td></tr><tr><td>CorsRegistration</td><td>allowCredentials</td><td>否</td><td>Access-Control-Allow-Credentials</td><td>配置是否允许发送Cookie, 用于 凭证请求</td></tr><tr><td>CorsRegistration</td><td>allowedHeaders</td><td>否</td><td>Access-Control-Request-Headers</td><td>配置允许的自定义请求头, 用于 预检请求</td></tr><tr><td>CorsRegistration</td><td>exposedHeaders</td><td>否</td><td>Access-Control-Expose-Headers</td><td>配置响应的头信息,<br>在其中可以设置其他的头信息</td></tr></tbody></table><div class="simditor-resize-handle" contenteditable="false" style="display: none;"><br></div></div><p><br></p>

      </el-col>
    </el-row>

  </div>


</template>

<script>
  export default {
    data() {
      return {

      }
    },
    methods: {


    },
    mounted() {
    }
  }
</script>

<style lang="less">
  .el-row {
    margin-bottom: 20px;
    &:last-child {
      margin-bottom: 0;
    }
  }
  .el-col {
    border-radius: 4px;
  }
  .bg-purple-dark {
    background: #99a9bf;
  }
  .bg-purple {
    background: #d3dce6;
  }
  .bg-purple-light {
    background: #e5e9f2;
  }
  .grid-content {
    border-radius: 4px;
    min-height: 36px;
  }
  .row-bg {
    padding: 10px 0;
    background-color: #f9fafc;
  }

</style>
